/**
 * Dev-mode fixtures. Used when pywebview is not available (vite dev in browser).
 *
 * NOT the source of truth — that's `glassbox/fixtures/*.json`, generated by
 * running sisa.py with varied configs. These ts fixtures mirror that output
 * shape and are kept thin on purpose: real numbers will replace them at T-2h.
 */
import type { Analysis, CaptionFraming, Splice, SpliceCatalog } from '@/types/analysis'

export const baseline: Analysis = {
  id: 'baseline',
  caption: 'The model predicts >$50K income for 31% of men but only 11% of women, even when other features are held equal.',
  panels: {
    dpd:      { value: 0.198, history: [{ step: 0, value: 0.198 }] },
    dir:      { value: 0.355, history: [{ step: 0, value: 0.355 }] },
    eod:      { value: 0.071, history: [{ step: 0, value: 0.071 }] },
    accuracy: { privileged: 0.847, unprivileged: 0.918, history: [
      { step: 0, value: 0.847 },
    ] },
    flags: [
      { attribute: 'sex', metric: 'disparate_impact_ratio', severity: 'HIGH',
        value: 0.355, threshold: 0.8,
        message: "'sex': disparate impact 0.355 < 0.8 (80% rule)" },
      { attribute: 'sex', metric: 'demographic_parity_diff', severity: 'HIGH',
        value: 0.198, threshold: 0.10,
        message: "'sex': demographic parity gap 0.198 > 0.10" },
    ],
  },
}

const placeholder = (id: string, caption: string, dpd: number, dir_: number, eod: number, acc_p: number, acc_u: number): Analysis => ({
  id,
  caption,
  panels: {
    dpd:      { value: dpd, history: [{ step: 0, value: 0.198 }, { step: 1, value: dpd }] },
    dir:      { value: dir_, history: [{ step: 0, value: 0.355 }, { step: 1, value: dir_ }] },
    eod:      { value: eod, history: [{ step: 0, value: 0.071 }, { step: 1, value: eod }] },
    accuracy: { privileged: acc_p, unprivileged: acc_u, history: [
      { step: 0, value: 0.847 }, { step: 1, value: (acc_p + acc_u) / 2 },
    ] },
    flags: [],
  },
})

const fixtures: Record<string, Analysis> = {
  baseline,
  'baseline__unlearn_unlearn-male-high-conf': placeholder(
    'unlearn-male', 'After unlearning 1,247 high-confidence male positives, the income-prediction gap drops from 19.8pp to 4.1pp.',
    0.041, 0.812, 0.029, 0.831, 0.840),
  'baseline__reweight_reweight-sex': placeholder(
    'reweight-sex', 'Rebalancing sample weights closes the disparate impact gap from 0.36 to 0.91.',
    0.027, 0.910, 0.018, 0.829, 0.835),
  'baseline__smote_smote-sex': placeholder(
    'smote-sex', 'SMOTE adds 4,200 synthetic female-positive samples; the model now matches its prediction rates within 2 percentage points.',
    0.019, 0.943, 0.012, 0.821, 0.828),
  'baseline__threshold_threshold-sex': placeholder(
    'threshold-sex', 'Group-specific thresholds equalize positive prediction rates without retraining. Accuracy drops 3pp.',
    0.008, 0.976, 0.041, 0.812, 0.819),
  'baseline__fairlearn_fairlearn-sex-dp': placeholder(
    'fairlearn-sex', 'Fairlearn DemographicParity reduction enforces equal positive rates as a hard training constraint.',
    0.005, 0.983, 0.022, 0.823, 0.829),
  'baseline__unlearn_unlearn-white-high-conf': placeholder(
    'unlearn-white', 'After unlearning 892 high-confidence white positives, the race-axis prediction gap drops from 14.2pp to 3.6pp.',
    0.036, 0.844, 0.028, 0.834, 0.839),
  'baseline__reweight_reweight-race': placeholder(
    'reweight-race', 'Rebalancing by race closes the disparate impact ratio to 0.88.',
    0.024, 0.880, 0.019, 0.831, 0.837),
  'baseline__smote_smote-race': placeholder(
    'smote-race', 'SMOTE adds synthetic minority-race positives; race-axis bias falls within the 80% rule.',
    0.018, 0.921, 0.014, 0.825, 0.831),
}

export function applyFixtureSplice(headId: string, splice: Splice): Analysis {
  const fixtureId = `${headId}__${splice.kind}_${splice.id}`
  return fixtures[fixtureId] ?? fixtures.baseline
}

export const spliceCatalog: SpliceCatalog = [
  { id: 'unlearn-male-high-conf', kind: 'unlearn', label: 'Unlearn high-confidence male positives',
    primitive: 'unlearn', magnitude: 0.7,
    args: { confidence: 0.75, max_pct: 0.05, attribute: 'sex' } },
  { id: 'reweight-sex', kind: 'reweight', label: 'Rebalance sample weights by sex',
    primitive: 'reweight', magnitude: 0.5,
    args: { attribute: 'sex' } },
  { id: 'smote-sex', kind: 'smote', label: 'SMOTE oversample minority sex',
    primitive: 'smote', magnitude: 0.6,
    args: { attribute: 'sex' } },
  { id: 'threshold-sex', kind: 'threshold', label: 'Per-group decision threshold (sex)',
    primitive: 'threshold', magnitude: 0.3,
    args: { attribute: 'sex', target_rate: 0.30 } },
  { id: 'fairlearn-sex-dp', kind: 'fairlearn', label: 'Fairlearn DemographicParity (sex)',
    primitive: 'fairlearn', magnitude: 0.8,
    args: { attribute: 'sex', constraint: 'DemographicParity' } },
  { id: 'unlearn-white-high-conf', kind: 'unlearn', label: 'Unlearn high-confidence white positives',
    primitive: 'unlearn', magnitude: 0.7,
    args: { confidence: 0.75, max_pct: 0.05, attribute: 'race' } },
  { id: 'reweight-race', kind: 'reweight', label: 'Rebalance sample weights by race',
    primitive: 'reweight', magnitude: 0.5,
    args: { attribute: 'race' } },
  { id: 'smote-race', kind: 'smote', label: 'SMOTE oversample minority race',
    primitive: 'smote', magnitude: 0.6,
    args: { attribute: 'race' } },
]

const captions: Record<string, Record<CaptionFraming, string>> = {
  'unlearn-male-high-conf': {
    accept:    'If you accept this unlearn, the model stops over-predicting >$50K for men by removing 1,247 of its most overconfident male-positive training samples.',
    reject:    'If you reject this, the model continues to predict >$50K for men 19.8 percentage points more often than for women.',
    committed: 'Unlearned 1,247 high-confidence male positives. The income-prediction gap fell from 19.8pp to 4.1pp.',
  },
  'reweight-sex': {
    accept:    'If you accept this reweighting, every female-positive training sample gets 2.4× the loss weight, lifting the disparate impact ratio from 0.36 to 0.91.',
    reject:    'If you reject this, the model keeps treating women as 64% less likely to deserve a positive prediction.',
    committed: 'Rebalanced sample weights by sex. Disparate impact ratio rose from 0.36 to 0.91.',
  },
  'smote-sex': {
    accept:    'If you accept SMOTE, the training set gains 4,200 synthetic female-positive samples and the model matches its prediction rates within 2 percentage points.',
    reject:    'If you reject this, the model continues to predict >$50K for 31% of men and 11% of women.',
    committed: 'Added 4,200 synthetic female-positive samples via SMOTE. Prediction rates now within 2pp.',
  },
  'threshold-sex': {
    accept:    'If you accept group-specific thresholds, the model uses 0.62 for men and 0.41 for women, equalizing positive prediction rates without retraining.',
    reject:    'If you reject this, every group sees the same 0.50 cutoff and the disparate impact stays below the 80% rule.',
    committed: 'Set per-group thresholds (0.62 men, 0.41 women). Positive rates now within 1pp.',
  },
  'fairlearn-sex-dp': {
    accept:    'If you accept this constraint, training enforces demographic parity directly. The model gives up 2pp of accuracy in exchange for near-zero gap.',
    reject:    'If you reject this, the model keeps optimizing accuracy alone and the disparate impact ratio stays at 0.36.',
    committed: 'Trained with DemographicParity constraint. Demographic parity gap is now 0.5pp.',
  },
  'unlearn-white-high-conf': {
    accept:    'If you accept this unlearn, the model stops over-predicting >$50K for white workers by removing 892 of its most overconfident white-positive training samples.',
    reject:    'If you reject this, the model continues to predict >$50K for white workers 14.2 percentage points more often than for non-white workers.',
    committed: 'Unlearned 892 high-confidence white positives. The race-axis gap fell from 14.2pp to 3.6pp.',
  },
  'reweight-race': {
    accept:    'If you accept this reweighting, every non-white-positive training sample gets 1.9× the loss weight, lifting the disparate impact ratio from 0.51 to 0.88.',
    reject:    'If you reject this, the model keeps treating non-white workers as 49% less likely to deserve a positive prediction.',
    committed: 'Rebalanced sample weights by race. Disparate impact ratio rose from 0.51 to 0.88.',
  },
  'smote-race': {
    accept:    'If you accept SMOTE, the training set gains 3,100 synthetic non-white-positive samples and the model brings race-axis bias within the 80% rule.',
    reject:    'If you reject this, the model continues to predict >$50K for white workers 14pp more often than for non-white workers.',
    committed: 'Added 3,100 synthetic non-white-positive samples via SMOTE. Race-axis bias now within 80% rule.',
  },
}

export function captionFor(spliceId: string, framing: CaptionFraming): string {
  return captions[spliceId]?.[framing] ?? ''
}
